# Generated by Django 4.2 on 2023-04-21 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
