# Generated by Django 4.2.1 on 2023-05-26 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('laboratories', '0002_branch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.AlterModelOptions(
            name='branch',
            options={'verbose_name_plural': 'Branches'},
        ),
        migrations.RemoveField(
            model_name='laboratory',
            name='address',
        ),
        migrations.RemoveField(
            model_name='laboratory',
            name='city',
        ),
        migrations.RemoveField(
            model_name='laboratory',
            name='email',
        ),
        migrations.RemoveField(
            model_name='laboratory',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='laboratory',
            name='state',
        ),
        migrations.AddField(
            model_name='branch',
            name='address',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='city',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='lab',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='laboratories.laboratory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='branch',
            name='phone_number',
            field=models.CharField(default='08140585844', max_length=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='branch',
            name='state',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='laboratory',
            name='services',
            field=models.ManyToManyField(help_text='Select a feature for this project', to='laboratories.service'),
        ),
    ]
