# Generated by Django 4.1.7 on 2023-03-23 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='animal_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.category'),
        ),
    ]
