# Generated by Django 4.1.7 on 2023-03-23 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_animal_animal_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='last_vaccination_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='next_vaccination_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
