# Generated by Django 4.1.7 on 2023-03-24 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_appointment_symptoms'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='Symptoms',
            new_name='symptoms',
        ),
        migrations.AddField(
            model_name='animal',
            name='animal_slug',
            field=models.SlugField(default='myslug', max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
