# Generated by Django 4.1.7 on 2023-03-31 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0007_bankaccount'),
        ('clients', '0006_alter_animal_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='appointment_doctor',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='doctors_appointments', to='doctors.doctor'),
            preserve_default=False,
        ),
    ]
