# Generated by Django 4.2 on 2023-04-06 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_appointment_appointment_doctor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='appointment',
            name='chat_room',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='meeting_room',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
