# Generated by Django 4.2 on 2023-05-01 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0011_alter_appointment_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animal',
            options={'ordering': ['name']},
        ),
    ]
