# Generated by Django 4.1.7 on 2023-03-20 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_service_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fee',
            name='fee',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
