# Generated by Django 4.1.7 on 2023-03-27 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_alter_animal_owner'),
        ('vaccinations', '0002_vaccine_age_of_vaccination_disease_vaccine_desease'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaccination',
            name='is_completed',
        ),
        migrations.AddField(
            model_name='vaccination',
            name='not_completed',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='vaccination',
            name='animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccinations', to='clients.animal'),
        ),
    ]
