# Generated by Django 4.2 on 2023-04-23 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccinations', '0003_remove_vaccination_is_completed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaccination',
            name='not_completed',
        ),
        migrations.AddField(
            model_name='vaccination',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
