# Generated by Django 4.1.7 on 2023-02-21 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='specialty',
        ),
        migrations.AddField(
            model_name='doctor',
            name='specialty',
            field=models.CharField(blank=True, choices=[('cat', 'Cat'), ('cattle', 'Cattle'), ('dog', 'Dog'), ('goat', 'Goat'), ('horse', 'Horse'), ('poultry', 'Poultry'), ('sheep', 'Sheep')], max_length=50, null=True),
        ),
    ]
