# Generated by Django 4.1.7 on 2023-02-24 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='induction_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
