# Generated by Django 4.1.7 on 2023-02-21 12:36

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_remove_doctor_specialty_doctor_specialty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='specialty',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('cat', 'Cat'), ('cattle', 'Cattle'), ('dog', 'Dog'), ('goat', 'Goat'), ('horse', 'Horse'), ('poultry', 'Poultry'), ('sheep', 'Sheep')], max_length=50, null=True),
        ),
    ]
