# Generated by Django 4.1.7 on 2023-02-24 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_alter_doctor_induction_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='induction_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
