# Generated by Django 4.1.7 on 2023-03-21 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0006_alter_openinghour_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(choices=[('Access', 'Access'), ('GTBank', 'GTBank'), ('9PSB', '9PSB'), ('OPAY', 'OPAY'), ('Kuda', 'Kuda'), ('First', 'First'), ('FCMB', 'FCMB'), ('UBA', 'UBA'), ('Moniepoint', 'Moniepoint'), ('Palmpay', 'Palmpay'), ('Wema', 'Wema'), ('Fidelity', 'Fidelity'), ('Jaiz', 'Jaiz'), ('Keystone', 'Keystone'), ('Polaris', 'Polaris'), ('Stanbic-ibtc', 'Stanbic-ibtc'), ('Sterling', 'Sterling'), ('Taj', 'Taj'), ('Union', 'Union'), ('Unity', 'Unity'), ('Zenith', 'Zenith')], max_length=100)),
                ('account_number', models.CharField(max_length=10)),
                ('account_name', models.CharField(max_length=50)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.doctor')),
            ],
        ),
    ]
