# Generated by Django 4.2 on 2023-04-08 19:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0009_meeting_doctor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meeting',
            options={'ordering': ('-date',)},
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='date_time',
        ),
        migrations.AddField(
            model_name='meeting',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='meeting',
            name='time',
            field=models.TimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='doctor_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='duration',
            field=models.PositiveSmallIntegerField(blank=True, default=30),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='timezone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='zoom_id',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
