# Generated by Django 4.2 on 2023-04-08 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0011_alter_meeting_date_alter_meeting_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meeting',
            old_name='doctor_email',
            new_name='zoom_email',
        ),
    ]
