# Generated by Django 4.2 on 2023-04-21 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0012_rename_doctor_email_meeting_zoom_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='zoom_email',
            field=models.EmailField(help_text='Your zoom email address', max_length=254),
        ),
    ]
