# Generated by Django 4.2.1 on 2023-05-30 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0013_alter_meeting_zoom_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='vcn_number',
            new_name='VCN_number',
        ),
    ]
