# Generated by Django 3.2 on 2023-06-23 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0014_rename_vcn_number_doctor_vcn_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='specialty',
            field=models.ManyToManyField(blank=True, help_text='You can select multiple specialties', null=True, to='doctors.AnimalSpecialty'),
        ),
    ]
