# Generated by Django 3.2 on 2023-06-23 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0015_alter_doctor_specialty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='specialty',
            field=models.ManyToManyField(blank=True, help_text='You can select multiple specialties', to='doctors.AnimalSpecialty'),
        ),
    ]
