# Generated by Django 4.2.1 on 2023-05-14 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_doctornotification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customernotification',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
