# Generated by Django 4.2.1 on 2023-05-14 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_customernotification_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctornotification',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
